// <auto-generated />
namespace OlwandleHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Fly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fly));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100056238_Fly"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
