// <auto-generated />
namespace OlwandleHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FlightChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlightChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202111100019011_FlightChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
