// <auto-generated />
namespace OlwandleHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class HotelTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HotelTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202110171754354_Hotel-Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
